# Roadiz travis setup
# Ambroise Maupate
node_js:
  - "lts/*"
  - "12"
  - "10"

php:
  - 7.4
  - 8.0

branches:
    except:
        - l10n_develop

jobs:
    include:
        - stage: "Default theme assets tests"
          language: node_js
          node_js: "lts/*"
          script: .travis/default_theme_assets.sh
        - stage: "Default theme assets tests"
          language: node_js
          node_js: "12"
          script: .travis/default_theme_assets.sh
        - stage: "Default theme assets tests"
          language: node_js
          node_js: "10"
          script: .travis/default_theme_assets.sh

        - stage: "Install assets tests"
          language: node_js
          node_js: "lts/*"
          script: .travis/install_assets.sh
        - stage: "Install assets tests"
          language: node_js
          node_js: "12"
          script: .travis/install_assets.sh
        - stage: "Install assets tests"
          language: node_js
          node_js: "10"
          script: .travis/install_assets.sh

        - stage: "Backoffice assets tests"
          language: node_js
          node_js: "lts/*"
          script: .travis/backoffice_assets.sh
        - stage: "Backoffice assets tests"
          language: node_js
          node_js: "12"
          script: .travis/backoffice_assets.sh
        - stage: "Backoffice assets tests"
          language: node_js
          node_js: "10"
          script: .travis/backoffice_assets.sh

        - stage: "PHP lint tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 7.4
          install: .travis/composer_install.sh
          script: .travis/php_lint.sh
        - stage: "PHP lint tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 8.0
          install: .travis/composer_install.sh
          script: .travis/php_lint.sh

        # php 7.4
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 7.4
          env:
            - DB=mysql
          before_script: .travis/php_unit_install.sh
          script: .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mariadb
          php:
            - 7.4
          env:
            - DB=mariadb
          before_script: .travis/php_unit_install.sh
          script: .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - postgresql
          php:
            - 7.4
          env:
            - DB=pgsql
          before_script: .travis/php_unit_install.sh
          script: .travis/php_unit.sh

        # php 8.0
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 8.0
          env:
            - DB=mysql
          before_script: .travis/php_unit_install.sh
          script: .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mariadb
          php:
            - 8.0
          env:
            - DB=mariadb
          before_script: .travis/php_unit_install.sh
          script: .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - postgresql
          php:
            - 8.0
          env:
            - DB=pgsql
          before_script: .travis/php_unit_install.sh
          script: .travis/php_unit.sh

