# Roadiz travis setup
# Ambroise Maupate
node_js:
  - "lts/*"
  - "12"
  - "10"

php:
  - 7.4
  - 8.0
  - nightly

stages:
    - "PHP lint tests"
    - "PHP unit tests"
    - "Install assets tests"
    - "Backoffice assets tests"
    - "Default theme assets tests"

branches:
    except:
        - l10n_develop

jobs:
    allow_failures:
        - php: 8.0
        - php: nightly

    include:
        - stage: "Default theme assets tests"
          language: node_js
          node_js: "lts/*"
          script: sh .travis/default_theme_assets.sh
        - stage: "Default theme assets tests"
          language: node_js
          node_js: "12"
          script: sh .travis/default_theme_assets.sh
        - stage: "Default theme assets tests"
          language: node_js
          node_js: "10"
          script: sh .travis/default_theme_assets.sh

        - stage: "Install assets tests"
          language: node_js
          node_js: "lts/*"
          script: sh .travis/install_assets.sh
        - stage: "Install assets tests"
          language: node_js
          node_js: "12"
          script: sh .travis/install_assets.sh
        - stage: "Install assets tests"
          language: node_js
          node_js: "10"
          script: sh .travis/install_assets.sh

        - stage: "Backoffice assets tests"
          language: node_js
          node_js: "lts/*"
          script: sh .travis/backoffice_assets.sh
        - stage: "Backoffice assets tests"
          language: node_js
          node_js: "12"
          script: sh .travis/backoffice_assets.sh
        - stage: "Backoffice assets tests"
          language: node_js
          node_js: "10"
          script: sh .travis/backoffice_assets.sh

        - stage: "PHP lint tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 7.4
          install: sh .travis/composer_install.sh
          script: sh .travis/php_lint.sh
        - stage: "PHP lint tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 8.0
          install: sh .travis/composer_install.sh
          script: sh .travis/php_lint.sh
        - stage: "PHP lint tests"
          language: php
          sudo: required
          services:
            - mysql
          php: nightly
          install: sh .travis/composer_install.sh
          script: sh .travis/php_lint.sh

        # php 7.4
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 7.4
          env:
            - DB=mysql
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mariadb
          php: 7.4
          env:
            - DB=mariadb
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - postgresql
          php: 7.4
          env:
            - DB=pgsql
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh

        # php 8.0
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mysql
          php: 8.0
          env:
            - DB=mysql
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mariadb
          php: 8.0
          env:
            - DB=mariadb
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - postgresql
          php: 8.0
          env:
            - DB=pgsql
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh

        # php nightly
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mysql
          php: nightly
          env:
            - DB=mysql
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - mariadb
          php: nightly
          env:
            - DB=mariadb
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh
        - stage: "PHP unit tests"
          language: php
          sudo: required
          services:
            - postgresql
          php: nightly
          env:
            - DB=pgsql
          before_script: sh .travis/php_unit_install.sh
          script: sh .travis/php_unit.sh

