version: "3"
services:
    # Test services
    db:
        image: postgres:12.1
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: adminer
        ports:
            - 8090:8080

volumes:
    db_data:
