# This route is required!
homePage:
    path:     /
    defaults:
        _controller: Themes\DefaultTheme\DefaultThemeApp::homeAction
homePageLocale:
    path:     /{_locale}
    defaults:
        _controller: Themes\DefaultTheme\DefaultThemeApp::homeAction
        _locale: en
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

contactPage:
    path:     /contact
    defaults:
        _controller: Themes\DefaultTheme\Controllers\ContactController::indexAction
        _locale: en
contactPageLocale:
    path:     /{_locale}/contact
    defaults:
        _controller: Themes\DefaultTheme\Controllers\ContactController::indexAction
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

searchPage:
    path:     /search
    defaults:
        _controller: Themes\DefaultTheme\Controllers\SearchController::defaultAction
        _locale: en
searchPageLocale:
    path:     /{_locale}/search
    defaults:
        _controller: Themes\DefaultTheme\Controllers\SearchController::defaultAction
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

thanksPage:
    path: /{_locale}/contact/thank-you
    defaults:
        _controller: Themes\DefaultTheme\Controllers\ContactController::thankAction
        _locale: "en"
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

thanksPageLocale:
    path:     /{_locale}/contact/thank-you
    defaults:
        _controller: Themes\DefaultTheme\Controllers\ContactController::thankAction
    requirements:
        _locale: "[a-z]{2}_?[A-Z]{0,2}"

sitemap:
    path: /sitemap.xml
    defaults:
        _controller: Themes\DefaultTheme\Controllers\SitemapController::sitemapAction

defaultRemoveTrailingSlash:
    path: /{url}
    defaults:
        _controller: Themes\DefaultTheme\DefaultThemeApp::removeTrailingSlashAction
    requirements:
        url: .*/$
    methods: [GET]
