---
appNamespace: "chooseAnUniqueNameForYourApp"
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "localhost"
    user: ""
    password: ""
    dbname: ""
    charset: utf8mb4
    default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
        row_format: DYNAMIC
# http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
# If null or empty, Roadiz will try to detect best cache driver available
cacheDriver:
    type: array
    host: ~
    port: ~
security:
    secret: "change#this#secret#very#important"
    session_name: roadiz_token
    # Switch session cookie secure to TRUE ONLY if your
    # website is served with HTTPS only
    session_cookie_secure: false
    session_cookie_httponly: true
    # Change default password algorithm from sha512 to argon2i
    algorithm: argon2i
mailer:
    type: ~
    host: "localhost"
    port: 25
    encryption: ~
    username: ""
    password: ""
themes:
    - classname: \Themes\DefaultTheme\DefaultThemeApp
      hostname: '*'
      routePrefix: ''
additionalServiceProviders:
    - \Themes\DefaultTheme\Services\DefaultThemeServiceProvider
additionalCommands:
    - \Themes\DefaultTheme\Commands\DefaultThemeCommand
# Image intervention and Intervention Request
# settings for generating image on the fly
assetsProcessing:
    # gd or imagick (gd does not support TIFF and PSD formats)
    driver: gd
    defaultQuality: 95
    # pixel size limit () after roadiz
    # should create a smaller copy.
    maxPixelSize: 2500
    jpegoptimPath: ~
    pngquantPath: ~
# Choose a Doctrine strategy for NodesSources
# inheritance classes. BE CAREFUL, if you change this
# setting after creating content in your website, all
# node-sources data will be lost.
inheritance:
    type: single_table
#solr:
#    endpoint:
#        localhost:
#            host: "localhost"
#            port: "8983"
#            path: "/"
#            core: "mycore"
#            timeout: 3
#            username: ""
#            password: ""

#
# Reverse proxy invalidation
#
#reverseProxyCache:
#    cloudflare:
#        zone: cloudflare-zone
#        bearer: ~
#        email: ~
#        key: ~
#
#    frontend:
#        varnish:
#            host: varnish_roadiz
#            domainName: roadiz.test
