version: '3'
services:
    db:
        build:
            # Custom image for file permissions
            context: ./docker/mysql
            args:
                USER_UID: ${USER_UID}
        networks:
            default:
        volumes:
            - "./.data/db:/var/lib/mysql:delegated"
            - "./docker/mysql/performances.cnf:/etc/mysql/conf.d/performances.cnf"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80/tcp
        networks:
            - default
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    app:
        build:
            context: ./docker/php72-nginx-alpine
            args:
                USER_UID: ${USER_UID}
        ports:
            - ${APP_PORT}:80/tcp
        depends_on:
            - db
            - solr
        links:
            - solr:solr
        volumes:
            - ./:/var/www/html:cached
        environment:
            APP_CACHE: ${APP_CACHE}
            USER_UID: ${USER_UID}
        networks:
            # Use your docker reverse-proxy service network to
            # serve app on your defined HOSTNAME (Traefik)
            frontproxynet:
            default:
        labels:
            # Replace example by your service name
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}.rule=Host(${HOSTNAME})"
            - "traefik.http.routers.${APP_NAMESPACE}.service=${APP_NAMESPACE}"

    solr:
        build:
            # Custom image for file permissions
            context: ./docker/solr
            args:
                USER_UID: ${USER_UID}
        ports:
            - "${SOLR_PORT}:8983/tcp"
        volumes:
            - "./.data/solr:/var/solr:delegated"
        command:
            - solr-precreate
            - roadiz
        environment:
            SOLR_UID: ${USER_UID}
            SOLR_GID: ${USER_UID}
        networks:
            - default

    mailer:
        image: mailhog/mailhog
        networks:
            - default
        ports:
            - ${PUBLIC_MAILER_PORT}:8025/tcp

networks:
    frontproxynet:
        external: true
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/16
