---
name: "Install theme"
author: "Ambroise Maupate"
copyright: "Ambroise Maupate and Julien Blanchet"
themeDir: "Install"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "1.7.0"
importFiles:
    roles:
        - "Resources/import/roles.json"
    groups: []
    settings:
        - "Resources/import/settings.json"
    nodetypes: []
